### PR TITLE
Issue #37 Added possibility to pull specific files

### PR DESCRIPTION
**Pull request by pierrerolland**
https://github.com/openl10n/openl10n-cli/issues/37

### CODE REVIEW

**Comment by romaindlf** [comment]
:+1:

**Comment by MattKetmo** [comment]
Merged via b052f11
Thanks

**Comment by jdeniau** [comment]
Hi @MattKetmo . Is it possible to drop a tag for this feature ?

**Comment by MattKetmo** [comment]
@jdeniau done (https://github.com/openl10n/openl10n-cli/releases/tag/v0.2.1)

**Comment by jdeniau** [comment]
Thanks!

**Pull request closed without merging**
